### ISSUE TITLE
Wrong implementation of Nat add

### ISSUE THREAD

**Issue by LoPoHa** [moonad/Base.fm#10]
The commit https://github.com/moonad/Formality-Base/commit/513744e6899cdc411f75d47c5573bcde18ff9c19 added a wrong result for the match on `zero` case for `m`.
It should return `n` instead of `zero`.

The test the bottom only works because `n <= m` (in this case `=`)

(Sorry for not making a pull request, i can't test my changes atm.)

**Comment by VictorTaelin** [comment]
Great catch again! Thanks.
